language: c

dist: xenial

os:
 - linux
 - osx

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -f /usr/local/include/c++ ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mlkit ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L -o smlpkg-bin-dist-darwin.tgz https://github.com/diku-dk/smlpkg/releases/download/v0.1.3/smlpkg-bin-dist-darwin.tgz ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar xzf smlpkg-bin-dist-darwin.tgz ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y mlton make ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L -o smlpkg-bin-dist-linux.tgz https://github.com/diku-dk/smlpkg/releases/download/v0.1.3/smlpkg-bin-dist-linux.tgz ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xzf smlpkg-bin-dist-linux.tgz ; fi

install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then SMLPKG=smlpkg-bin-dist-darwin/bin/smlpkg make clean all ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then SMLPKG=smlpkg-bin-dist-linux/bin/smlpkg MLCOMP='mlton -output run' make clean all ; fi

script:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make test ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MLCOMP=mlton make test ; fi
